### ISSUE TITLE
Feature request: Exclude URLs even in plaintext

### ISSUE THREAD

**Issue by hata6502** [textlint-rule/textlint-rule-sentence-length#15]
I'd appreciate it if exclude URLs even in plaintext. :pray:

Input: `test.txt`  (plaintext)

```test.txt
https://example.com/longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong

```

Current behavior:

```
  1:1  error  Line 1 sentence length(104) exceeds the maximum sentence length of 100.
Over 4 characters  sentence-length

```

Requested behavior: Exclude URLs even in plaintext, and the error is not occured.

**Comment by azu** [comment]
In plain text, textlint can not detect the URL as a Link node.

https://github.com/textlint-rule/textlint-rule-sentence-length#options
Can you resolve this issue with `exclusionPatterns` option?

If you means that adding "Except Link", we need to add new option like `skipLink`.

**Comment by hata6502** [comment]
@azu Thank you!
I resolved with `exclusionPatterns`.

```js
{
  ruleId: 'sentence-length',
  rule: textlintRuleSentenceLength,
  options: {
    // CC BY-SA 4.0
    exclusionPatterns: ['/https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)/'],
  },
}
```

Regex from [Stack Overflow](https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url).
Asked by [bigbob](https://stackoverflow.com/users/460129/bigbob), answered by [Daveo](https://stackoverflow.com/users/165839/daveo).

---

But... this regex is tiny complex, and excluding URLs is a general usage.
Would you implement this feature with (url-regex-safe)[https://github.com/niftylettuce/url-regex-safe] by default?
I think that `skipLink` is not needed because this feature can be enabled by default.

**Comment by azu** [comment]
It is case by case.

I want to count the following case.

```markdown
This is [example](https://example.com/longlonglonglonglonglonglonglong).
```

I agree that skip counting the following case.
However, some users want to count it. It should be an option.
(It is an actually long text.)

```markdown
This is <https://example.com/longlonglonglonglonglonglonglonglonglonglong>.
```

Logics:

- if `Link` node's `url === `Link` node's value 
  - treat it as 0 length text

If the above logic going to be implemented, `.txt` still shows the same error.
because, [@textlint/textlint-plugin-text](https://github.com/textlint/textlint/tree/master/packages/%40textlint/textlint-plugin-text) does not parse URL-like string as `Link` node.

I disagree that the rule uses URL Regexp because I do not want to implement the same URL Regexp in various rules.
This task should be implemented in the plugin/parser.
